Feature/accommodation filtering searching 3.9
booking-app-team-2/bookie-backend pull request #70
Opened 2023-12-27 17:21 UTC by GojkoVuckovic

Added location searching

2023-12-27 17:24 UTC, borismarkovsv73 approved these changes

2023-12-27 18:55 UTC, darkokos requested changes
The general idea of finding two accommodations in relative proximity applied here is fine. However, the implementation isn't.

First and foremost, the separation of concerns on the service layer, here, is all over the place. The private static methods in the accommodation service should point to this, seeing as the accommodation service holds no state regarding locations, which should, in this fundamentally wrong way of thinking, justify the fact that these methods are static. This is a domain logic problem that a service doing business logic should not go into so much detail to solve. Such behaviour makes the accommodation service have more responsibilities than the one it needs to have. It also creates a bottleneck because these methods would not necessarily be used only by the accommodation service, seeing as they are closely tied to locations themselves. So, this code is not reusable.

Next, the methods talked about above are also not fully covering the logic they are supposed to cover. Again, the accommodation service should only care about whether the locations of the two given accommodations are in proximity (or, in the same city, in this case). This, combined with the lack of whitespaces in this code snippet, makes the code very unreadable.

Lastly, I have minor concerns with the success rate of this functionality, like what would happen if the Nominative API, consulted here, returns an erroneous response or faulty JSON, seeing as that is something that one of these methods check, but never react to. Also, the location sent by the search query is simply compared to the name of the city of a given accommodation, regardless of whether or not that sent location is a city itself, or maybe a more detailed location, like, state, city, street name, street number, which should also be valid.

2023-12-28 11:01 UTC, darkokos approved these changes
Better, now

2023-12-28 12:28 UTC, borismarkovsv73 approved these changes

2023-12-28 12:46 UTC, merged