Feature/image view
booking-app-team-2/bookie-backend pull request #74
Opened 2024-01-13 15:38 UTC by GojkoVuckovic

2024-01-13 18:45 UTC, borismarkovsv73 approved these changes

2024-01-14 13:30 UTC, darkokos commented on src/main/java/booking_app_team_2/bookie/service/ImageServiceImpl.java
While deleting an image, you are not only supposed to remove the reference to it from the DB, but, rather, delete it from the directory where it was saved.<br>

While deleting objects from the DB, you shouldn't manually set the isDeleted flag, but call the repository method for removing an entity.<br>

Next time, consider using updated, maintained classes like Instant for getting the Unix timestamp, as methods like currentTimeMillis and methods from Date are "unofficially" deprecated and are considered unsafe.

2024-01-14 13:30 UTC, darkokos requested changes
While deleting an image, you are not only supposed to remove the reference to it from the DB, but, rather, delete it from the directory where it was saved.

While deleting objects from the DB, you shouldn't manually set the isDeleted flag, but call the repository method for removing an entity.

Next time, consider using updated, maintained classes like Instant for getting the Unix timestamp, as methods like currentTimeMillis and methods from Date are "unofficially" deprecated and are considered unsafe.

2024-01-14 16:21 UTC, darkokos approved these changes
The method for posting an image that you have created does not allow for having one image linked to multiple accommodations and neither does the domain model or the DB schema, so your method for deleting an image is constantly going to be doing unnecessary work.<br>

After removing an image from the collection of images within an accommodation and persisting the accommodation, calling the remove method upon the image itself is redundant, as the collection of images within the Accommodation class has orphan removal set to true.<br>

Saving images within the project is not optimal, as they are large and will be pushed/pulled to/from the repository every time.

2024-01-14 16:42 UTC, borismarkovsv73 approved these changes

2024-01-15 10:59 UTC, merged